[package]
name = "porch-camera"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47.1", features = [ "fs", "macros", "rt", "rt-multi-thread", "sync", "time" ] }
turbojpeg = { version ="1.3.3", default-features = false, features = [ "cmake", "require-simd" ] }
uvc = { path = "vendor/uvc", features = [ "vendor" ] }
